spring:
    application:
        name: homework

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/homework
        username: root
        password: password

    web:
        resources:
            static-locations: file:D:/homework/image/

server:
    port: 9999

resources:
    image: file:D:/homework/image/
